// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ8WUcshErfao-dRgQcNTrq5RaEjPCxIw',
    appId: '1:384796980672:web:6f6f6324c238f263028425',
    messagingSenderId: '384796980672',
    projectId: 'bus-tracking-9fb0c',
    authDomain: 'bus-tracking-9fb0c.firebaseapp.com',
    storageBucket: 'bus-tracking-9fb0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWal2BRRjkx_SazI-NFu6TqvIFB6cra60',
    appId: '1:384796980672:android:cdc75d8fe96c7ba8028425',
    messagingSenderId: '384796980672',
    projectId: 'bus-tracking-9fb0c',
    storageBucket: 'bus-tracking-9fb0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMpu7of9yLMuBa_4w6oqa68mMwLsE6Xiw',
    appId: '1:384796980672:ios:5c71abea3d42ec92028425',
    messagingSenderId: '384796980672',
    projectId: 'bus-tracking-9fb0c',
    storageBucket: 'bus-tracking-9fb0c.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMpu7of9yLMuBa_4w6oqa68mMwLsE6Xiw',
    appId: '1:384796980672:ios:5c71abea3d42ec92028425',
    messagingSenderId: '384796980672',
    projectId: 'bus-tracking-9fb0c',
    storageBucket: 'bus-tracking-9fb0c.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ8WUcshErfao-dRgQcNTrq5RaEjPCxIw',
    appId: '1:384796980672:web:b9ca817c2b5e26ec028425',
    messagingSenderId: '384796980672',
    projectId: 'bus-tracking-9fb0c',
    authDomain: 'bus-tracking-9fb0c.firebaseapp.com',
    storageBucket: 'bus-tracking-9fb0c.firebasestorage.app',
  );
}
